# Generated by Django 5.2.1 on 2026-05-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, choices=[('Foundation', 'Foundation'), ('Diploma', 'Diploma'), ('Degree', 'Degree')], max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(blank=True, choices=[('Data Science', 'Data Science'), ('Electronic Systems', 'Electronic Systems'), ('Management', 'Management'), ('Aerospace', 'Aerospace')], max_length=50),
        ),
    ]
