# Generated by Django 5.1.6 on 2025-03-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='roll_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
