# Generated by Django 5.1.6 on 2025-12-26 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventRegistration',
        ),
        migrations.DeleteModel(
            name='EventSubmission',
        ),
    ]
