# Generated by Django 5.1.6 on 2025-12-26 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_auth', '0002_delete_eventregistration_delete_eventsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('event_type', models.CharField(choices=[('DSA', 'DSA'), ('IDEA', 'Ideathon'), ('HACK', 'Hackathon')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone must be 10 digits')])),
                ('email', models.EmailField(max_length=254)),
                ('is_team', models.BooleanField(default=False)),
                ('team_emails', models.JSONField(blank=True, null=True)),
                ('track', models.CharField(blank=True, max_length=20, null=True)),
                ('accepted_rules', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('event_id', 'email')},
            },
        ),
        migrations.CreateModel(
            name='EventSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('submission_link', models.URLField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('event_id', 'email')},
            },
        ),
    ]
