# Generated by Django 5.1.6 on 2025-03-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_auth', '0002_alter_studentuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='roll_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
