# Generated by Django 5.1.6 on 2025-03-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_auth', '0002_rename_student_studentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='roll_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
