# Generated by Django 5.2.1 on 2026-02-24 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_auth', '0003_eventregistration_eventsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='track',
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event_type',
            field=models.CharField(choices=[('Pen it down', 'Pen it down'), ('Talent Showcase', 'Talent Showcase'), ('From your lens', 'From your lens'), ('Vaak Yudh', 'Vaak Yudh')], max_length=30),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be 10 digits')]),
        ),
    ]
