# Generated by Django 5.1.6 on 2025-03-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_auth', '0004_alter_studentuser_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='roll_number',
            field=models.CharField(default=None, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
