# Generated by Django 5.2.1 on 2026-02-24 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_auth', '0004_remove_eventregistration_track_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='is_team',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='team_emails',
        ),
    ]
