# Generated by Django 5.1.6 on 2025-03-16 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_auth', '0005_alter_studentuser_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='level',
            field=models.CharField(blank=True, choices=[('FL', 'Foundation'), ('DP', 'Diploma'), ('DG', 'Degree')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='program',
            field=models.CharField(blank=True, choices=[('DS', 'Data Science'), ('ES', 'Electronic Systems')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='roll_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
