# Generated by Django 5.2.1 on 2026-02-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_auth', '0005_remove_eventregistration_is_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='event_type',
            field=models.CharField(choices=[('Pen It Down', 'Pen It Down'), ('Talent Showcase', 'Talent Showcase'), ('From Your Lens', 'From Your Lens'), ('Vaak – Yuddh', 'Vaak – Yuddh')], max_length=30),
        ),
    ]
