# Generated by Django 5.1.6 on 2025-06-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_auth', '0006_alter_studentuser_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
