# Generated by Django 5.2.1 on 2026-02-24 01:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_auth', '0006_alter_eventregistration_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubmission',
            name='agree_to_rules',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsubmission',
            name='awarness',
            field=models.CharField(choices=[('Kaziranga Groups', 'Kaziranga Groups'), ('Email/WhatsApp Promotions', 'Email/WhatsApp Promotions'), ('Friends', 'Friends')], default='Friends', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsubmission',
            name='event_type',
            field=models.CharField(choices=[('Pen It Down', 'Pen It Down'), ('Talent Showcase', 'Talent Showcase'), ('From Your Lens', 'From Your Lens'), ('Vaak – Yuddh', 'Vaak – Yuddh')], default='Pen It Down', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsubmission',
            name='house',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsubmission',
            name='level',
            field=models.CharField(choices=[('Foundation', 'Foundation'), ('Diploma', 'Diploma'), ('Degree', 'Degree')], default='Degree', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsubmission',
            name='name',
            field=models.CharField(default='Time pass', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsubmission',
            name='permission_for_social',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsubmission',
            name='phone',
            field=models.CharField(default='1234567890', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be 10 digits')]),
            preserve_default=False,
        ),
    ]
