# Generated by Django 5.1.6 on 2025-07-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_auth', '0007_alter_studentuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='google',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
