# Generated by Django 5.1.6 on 2025-07-27 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_auth', '0008_studentuser_google'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='google',
        ),
    ]
