# Generated by Django 5.1.6 on 2025-08-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_auth', '0009_remove_studentuser_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='level',
            field=models.CharField(blank=True, choices=[('Foundation', 'Foundation'), ('Diploma', 'Diploma'), ('Degree', 'Degree')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='program',
            field=models.CharField(blank=True, choices=[('Data Science', 'Data Science'), ('Electronic Systems', 'Electronic Systems')], max_length=25, null=True),
        ),
    ]
