# Generated by Django 5.1.6 on 2025-08-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_auth', '0010_alter_studentuser_email_alter_studentuser_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='profile_pic',
            field=models.URLField(blank=True, default='https://static.vecteezy.com/system/resources/thumbnails/009/292/244/small_2x/default-avatar-icon-of-social-media-user-vector.jpg', null=True),
        ),
    ]
