# Generated by Django 5.1.6 on 2025-08-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_auth', '0011_alter_studentuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='program',
            field=models.CharField(blank=True, choices=[('DS', 'Data Science'), ('ES', 'Electronic Systems')], max_length=25, null=True),
        ),
    ]
