# Generated by Django 5.1.6 on 2025-08-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_auth', '0012_alter_studentuser_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='level',
            field=models.CharField(blank=True, choices=[('FL', 'Foundation'), ('DP', 'Diploma'), ('DG', 'Degree')], max_length=25, null=True),
        ),
    ]
