# Generated by Django 5.1.6 on 2025-11-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_auth', '0013_alter_studentuser_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootcampRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('roll', models.CharField(max_length=20)),
            ],
        ),
    ]
