# Generated by Django 5.2.1 on 2025-12-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_auth', '0014_bootcampregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcampregister',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='bootcampregister',
            name='roll',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
