# Generated by Django 5.1.6 on 2025-03-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('program', models.CharField(choices=[('DS', 'Data Science'), ('ES', 'Electronic Systems')], max_length=25)),
                ('level', models.CharField(choices=[('FL', 'Foundation'), ('DP', 'Diploma'), ('DG', 'Degree')], max_length=25)),
            ],
        ),
    ]
