# Generated by Django 5.1.6 on 2025-03-04 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_alter_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='weeks',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_number', models.IntegerField()),
                ('week_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('video_link', models.URLField()),
                ('duration', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture', to='lectures.course')),
            ],
        ),
    ]
