# Generated by Django 5.1.6 on 2025-03-04 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamp',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_stamps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_stamps', to='lectures.lecture'),
        ),
    ]
