# Generated by Django 5.1.6 on 2025-03-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0006_alter_timestamp_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamp',
            name='end_timestamp',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
