# Generated by Django 5.1.6 on 2025-04-09 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0007_alter_timestamp_end_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Foundation', 'Foundation'), ('Diploma', 'Diploma'), ('Degree', 'Degree')], max_length=15),
        ),
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.CharField(choices=[('Data Science', 'Data Science'), ('Electronic Systems', 'Electronic Systems')], max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='weeks',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
