# Generated by Django 5.1.6 on 2025-04-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0008_alter_course_id_alter_course_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('FL', 'Foundation'), ('DP', 'Diploma'), ('DG', 'Degree')], max_length=15),
        ),
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.CharField(choices=[('DS', 'Data Science'), ('ES', 'Electronic Systems')], max_length=20),
        ),
    ]
