# Generated by Django 5.1.6 on 2025-04-09 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0009_alter_course_level_alter_course_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
