# Generated by Django 5.1.6 on 2025-04-09 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0010_alter_lecture_lecture_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='week_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
            preserve_default=False,
        ),
    ]
