# Generated by Django 5.1.6 on 2025-04-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0011_lecture_week_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamp',
            name='name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
