# Generated by Django 5.1.6 on 2025-05-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0012_timestamp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
