# Generated by Django 5.1.6 on 2025-03-04 17:36

import groups.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('rules', models.TextField()),
                ('profile_pic', models.URLField()),
                ('members_count', models.IntegerField()),
                ('admin', models.OneToOneField(on_delete=models.SET(groups.models.Group.get_default_admin), related_name='group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
