# Generated by Django 5.1.6 on 2025-03-06 09:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_alter_comment_post_alter_comment_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commented_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
