# Generated by Django 5.1.6 on 2025-03-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_alter_group_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='admin',
        ),
    ]
