# Generated by Django 5.1.6 on 2025-03-17 14:58

import groups.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_remove_group_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(default=None, on_delete=models.SET(groups.models.Group.get_default_admin), related_name='group', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
