# Generated by Django 5.1.6 on 2025-03-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_group_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members_count',
        ),
    ]
