# Generated by Django 5.1.6 on 2025-04-04 14:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_remove_group_members_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postvotes',
            unique_together={('post', 'student')},
        ),
    ]
