# Generated by Django 5.1.6 on 2025-07-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0016_alter_postvotes_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='banner_pic',
            field=models.URLField(default=''),
        ),
    ]
