# Generated by Django 5.1.6 on 2025-07-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0017_group_banner_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='banner_pic',
            field=models.URLField(),
        ),
    ]
