# Generated by Django 5.1.6 on 2025-07-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0018_alter_group_banner_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
