# Generated by Django 5.1.6 on 2025-07-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='user',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
