# Generated by Django 5.2.1 on 2026-05-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
