# Generated by Django 5.2.1 on 2026-05-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_description_alter_resource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='tag',
            field=models.CharField(blank=True, choices=[('Institute', 'Institute'), ('Academic', 'Academic'), ('PYQs', 'PYQs'), ('Placements', 'Placements'), ('Internships', 'Internships'), ('Paradox(Fest)', 'Paradox(Fest)'), ('Books', 'Books'), ('Misc', 'Misc')], max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
